### ISSUE TITLE
ExecRaw does not respect OperationName option

### ISSUE THREAD

**Issue by bhoriuchi** [hasura/go-graphql-client#96]
ExecRaw takes options arguments but does not apply them. This causes issue when supplying multiple operations in a request and trying to execute a specific operation by name.

https://github.com/hasura/go-graphql-client/blob/master/graphql.go#L126

**Comment by hgiasac** [comment]
Hi,

Because you can input the raw GraphQL query string directly in `Exec` and `ExecRaw` methods, it doesn't worth manipulating the string to inject the operation name into it. We still add optional arguments for these methods for further extensions. However it doesn't mean we have to support all extensions.

**Comment by hgiasac** [comment]
Close this issue. Please reopen if you have further questions
